### PR TITLE
Issue33 create tests for command classify

### PR DESCRIPTION
**Pull request by xingwang**
- Used en-US.json for validating tests.
- Had to remove conflicting keywords from json file.

Closes (#33)

### CODE REVIEW

**Comment by jakkra** [comment]
This looks great! Nice work 👍 
Maybe we can manually import  '../locales/sv-SE' and '../locales/en-US' instead of using the langauge set in the config file alternatively forEach(file_in_locales). And then run the tests for all languages.

**Comment by jakkra** [comment]
Tested it and it works great! Also tested the Swedish commands, some are failing because I have ambiguous commands (not used anyway) which I will remove. If you want you can add all languages to the test (OK that some swedish tests fail), otherwise I'll do it myself?

**Comment by xingwang** [comment]
Sorry for the late response, was pretty busy today. I think the multiple language addition should be in its own test as this one is already pretty cluttered (maybe one for synonyms.js?). Otherwise, this is no longer a unit test for command_classify.js but more of an integration test.

**Comment by jakkra** [comment]
Ah okej! Yeah I guess that test would be to verify that synonyms doesn't have conflicting keywords. Maybe we could create two tests, one for classify and one for synonyms which both just use the test you created (remake it so that language file is an input parameter to it)

**Comment by xingwang** [comment]
You don't need to overcomplicate it. A simple forEach loop for each config that tests no command string contains another will do. This also keeps your test files separate from each other so there's no dependencies between test files.

**Pull request merged**
